void GenerateRandomData(int a[], int n);
void GenerateSortedData(int a[], int n);
void GenerateReverseData(int a[], int n);
void GenerateNearlySortedData(int a[], int n);
void GenerateData(int a[], int n, int dataType);
const int SMALL = 3000;
const int MEDIUM = 10000;
const int LARGE = 30000;
const int BIG = 100000;
const int VERYBIG = 300000;
